// <auto-generated />
using System;
using LogicFit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicFit.Infrastructure.Persistence.Migrations.ControlPlane
{
    [DbContext(typeof(ControlPlaneDbContext))]
    [Migration("20260825144155_InitialControlPlaneFoundation")]
    partial class InitialControlPlaneFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("audit_event_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("OccurredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("occurred_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RequestId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("request_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("result");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("target_type");

                    b.HasKey("AuditEventId")
                        .HasName("PK_audit_events");

                    b.ToTable("events", "audit");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.CredentialEntity", b =>
                {
                    b.Property<Guid>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("credential_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("credential_type");

                    b.Property<DateTime?>("LastRotatedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_rotated_at_utc");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("secret_hash");

                    b.Property<string>("SecretVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("secret_version");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("CredentialId")
                        .HasName("PK_iam_credentials");

                    b.HasIndex("UserId", "CredentialType")
                        .IsUnique()
                        .HasDatabaseName("UQ_iam_credentials_type");

                    b.ToTable("credentials", "iam");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.FeatureFlagEntity", b =>
                {
                    b.Property<Guid>("FeatureFlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("feature_flag_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("enabled");

                    b.Property<string>("FlagKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("flag_key");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("scope_type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("FeatureFlagId")
                        .HasName("PK_platform_feature_flags");

                    b.HasIndex("FlagKey", "ScopeType", "ScopeId")
                        .IsUnique()
                        .HasDatabaseName("UQ_platform_feature_flags_scope")
                        .HasFilter("[scope_id] IS NOT NULL");

                    b.ToTable("feature_flags", "platform");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.GymDatabaseEntity", b =>
                {
                    b.Property<Guid>("GymDatabaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("gym_database_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ConnectionSecretRef")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("connection_secret_ref");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("database_name");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("local")
                        .HasColumnName("environment");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("gym_id");

                    b.Property<DateTime?>("LastHealthAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_health_at_utc");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("SchemaVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("schema_version");

                    b.Property<string>("SeedVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("seed_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("GymDatabaseId")
                        .HasName("PK_platform_gym_databases");

                    b.HasIndex("GymId");

                    b.HasIndex("Environment", "DatabaseName")
                        .IsUnique()
                        .HasDatabaseName("UQ_platform_gym_databases_name");

                    b.ToTable("gym_databases", "platform");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.GymEntity", b =>
                {
                    b.Property<Guid>("GymId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("gym_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("provisioning")
                        .HasColumnName("status");

                    b.Property<string>("TimezoneName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasDefaultValue("Africa/Cairo")
                        .HasColumnName("timezone_name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("GymId")
                        .HasName("PK_platform_gyms");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_platform_gyms_org_slug");

                    b.ToTable("gyms", "platform");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.MfaFactorEntity", b =>
                {
                    b.Property<Guid>("MfaFactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("mfa_factor_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("FactorType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("totp")
                        .HasColumnName("factor_type");

                    b.Property<string>("SecretRef")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("secret_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("verified_at_utc");

                    b.HasKey("MfaFactorId")
                        .HasName("PK_iam_mfa_factors");

                    b.HasIndex("UserId");

                    b.ToTable("mfa_factors", "iam");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.MfaRecoveryCodeEntity", b =>
                {
                    b.Property<Guid>("RecoveryCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recovery_code_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("MfaFactorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("mfa_factor_id");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("RecoveryCodeId")
                        .HasName("PK_iam_mfa_recovery_codes");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_iam_mfa_recovery_codes_hash");

                    b.HasIndex("MfaFactorId");

                    b.HasIndex("UserId", "MfaFactorId", "UsedAtUtc", "RevokedAtUtc")
                        .HasDatabaseName("IX_iam_recovery_codes_active");

                    b.ToTable("mfa_recovery_codes", "iam");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.MigrationDefinitionEntity", b =>
                {
                    b.Property<Guid>("MigrationDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("migration_definition_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("checksum_sha256");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("FromVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("from_version");

                    b.Property<string>("MigrationKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("migration_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("approved")
                        .HasColumnName("status");

                    b.Property<string>("ToVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("to_version");

                    b.HasKey("MigrationDefinitionId")
                        .HasName("PK_migrations_definitions");

                    b.HasIndex("MigrationKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_migrations_definitions_key");

                    b.ToTable("definitions", "migrations");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.MigrationRunEntity", b =>
                {
                    b.Property<Guid>("MigrationRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("migration_run_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("error_code");

                    b.Property<string>("MigrationKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("migration_key");

                    b.Property<DateTime>("RequestedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("requested_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("running")
                        .HasColumnName("status");

                    b.HasKey("MigrationRunId")
                        .HasName("PK_migrations_runs");

                    b.ToTable("runs", "migrations");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.OrganizationEntity", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("OrganizationId")
                        .HasName("PK_platform_organizations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_platform_organizations_slug");

                    b.ToTable("organizations", "platform");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.PasswordResetTokenEntity", b =>
                {
                    b.Property<Guid>("PasswordResetTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("password_reset_token_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("RequestId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("request_id");

                    b.Property<string>("RequestedIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("requested_ip");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("PasswordResetTokenId")
                        .HasName("PK_iam_password_reset_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_iam_password_reset_tokens_hash");

                    b.HasIndex("UserId", "ExpiresAtUtc", "UsedAtUtc", "RevokedAtUtc")
                        .HasDatabaseName("IX_iam_password_reset_active");

                    b.ToTable("password_reset_tokens", "iam");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.PermissionEntity", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("permission_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("domain");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("permission_key");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("normal")
                        .HasColumnName("risk_level");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("PermissionId")
                        .HasName("PK_iam_permissions");

                    b.HasIndex("PermissionKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_iam_permissions_key");

                    b.ToTable("permissions", "iam");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("scope_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("RoleId")
                        .HasName("PK_iam_roles");

                    b.HasIndex("ScopeType", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_iam_roles_scope_name");

                    b.ToTable("roles", "iam");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.RolePermissionEntity", b =>
                {
                    b.Property<Guid>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_permission_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<string>("ScopeRuleJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scope_rule_json");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("RolePermissionId")
                        .HasName("PK_iam_role_permissions");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_iam_role_permissions_pair");

                    b.ToTable("role_permissions", "iam");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.SessionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("AbsoluteExpiresAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("absolute_expires_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("gym_id");

                    b.Property<DateTime?>("IdleExpiresAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("idle_expires_at_utc");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<bool>("MfaVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("mfa_verified");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("SessionKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("staff")
                        .HasColumnName("session_kind");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId")
                        .HasName("PK_iam_sessions");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_iam_sessions_token");

                    b.HasIndex("GymId", "UserId", "RevokedAtUtc")
                        .HasDatabaseName("IX_iam_sessions_gym");

                    b.HasIndex("UserId", "RevokedAtUtc", "ExpiresAtUtc")
                        .HasDatabaseName("IX_iam_sessions_user_active");

                    b.ToTable("sessions", "iam");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_login_at_utc");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId")
                        .HasName("PK_iam_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_iam_users_email");

                    b.ToTable("users", "iam");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.UserGymRoleEntity", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assignment_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("gym_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("scope_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("AssignmentId")
                        .HasName("PK_iam_user_gym_roles");

                    b.HasIndex("GymId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UX_iam_user_gym_roles_platform")
                        .HasFilter("[scope_type] = N'platform' AND [status] = N'active'");

                    b.HasIndex("UserId", "GymId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UX_iam_user_gym_roles_gym")
                        .HasFilter("[scope_type] = N'gym' AND [status] = N'active'");

                    b.HasIndex("UserId", "ScopeType", "GymId", "Status")
                        .HasDatabaseName("IX_iam_user_gym_roles_scope");

                    b.ToTable("user_gym_roles", "iam");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.CredentialEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany("Credentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.GymDatabaseEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.GymEntity", "Gym")
                        .WithMany("Databases")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.GymEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.OrganizationEntity", "Organization")
                        .WithMany("Gyms")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.MfaFactorEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany("MfaFactors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.MfaRecoveryCodeEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.MfaFactorEntity", "MfaFactor")
                        .WithMany()
                        .HasForeignKey("MfaFactorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany("MfaRecoveryCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MfaFactor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.PasswordResetTokenEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.RolePermissionEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.PermissionEntity", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.SessionEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.GymEntity", "Gym")
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.UserGymRoleEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.GymEntity", "Gym")
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("UserGymRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany("GymRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.GymEntity", b =>
                {
                    b.Navigation("Databases");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.OrganizationEntity", b =>
                {
                    b.Navigation("Gyms");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.PermissionEntity", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.RoleEntity", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserGymRoles");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("GymRoles");

                    b.Navigation("MfaFactors");

                    b.Navigation("MfaRecoveryCodes");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
