// <auto-generated />
using System;
using LogicFit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicFit.Infrastructure.Persistence.Migrations.Gym
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260825144011_InitialGymFoundation")]
    partial class InitialGymFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.AnatomyMappingEntity", b =>
                {
                    b.Property<Guid>("AnatomyMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("anatomy_mapping_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("asset_key");

                    b.Property<string>("BodyRegion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("body_region");

                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("muscle_id");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name_en");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<string>("RecordScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("record_scope");

                    b.Property<string>("SeedKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("seed_key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("source");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("source_version");

                    b.Property<string>("ViewCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("view_code");

                    b.HasKey("AnatomyMappingId")
                        .HasName("PK_seed_anatomy_mappings");

                    b.HasIndex("MuscleId");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_anatomy_mappings_seed");

                    b.ToTable("anatomy_mappings", "library");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.EquipmentEntity", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("equipment_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name_en");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<string>("RecordScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("record_scope");

                    b.Property<string>("SeedKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("seed_key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("source");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("source_version");

                    b.HasKey("EquipmentId")
                        .HasName("PK_seed_equipment");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_equipment_seed");

                    b.ToTable("equipment", "library");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.ExerciseCategoryEntity", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name_en");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<string>("RecordScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("record_scope");

                    b.Property<string>("SeedKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("seed_key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("source");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("source_version");

                    b.HasKey("CategoryId")
                        .HasName("PK_seed_exercise_categories");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_exercise_categories_seed");

                    b.ToTable("exercise_categories", "library");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.ExerciseEntity", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exercise_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<string>("CommonMistakesAr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("common_mistakes_ar");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DifficultyCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("difficulty_code");

                    b.Property<string>("InstructionsAr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instructions_ar");

                    b.Property<string>("InstructionsEn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instructions_en");

                    b.Property<string>("LegacyStatus")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("legacy_status");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("level_id");

                    b.Property<string>("MediaJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("media_json");

                    b.Property<string>("MovementPattern")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("movement_pattern");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name_en");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<Guid>("PrimaryMuscleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("primary_muscle_id");

                    b.Property<string>("RecordScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("record_scope");

                    b.Property<string>("SeedKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("seed_key");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("slug");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("source");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("source_version");

                    b.Property<string>("TipsAr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tips_ar");

                    b.HasKey("ExerciseId")
                        .HasName("PK_seed_exercises");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LevelId");

                    b.HasIndex("PrimaryMuscleId");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_exercises_seed");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_exercises_slug");

                    b.ToTable("exercises", "library");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.ExerciseEquipmentEntity", b =>
                {
                    b.Property<Guid>("ExerciseEquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exercise_equipment_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("equipment_id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exercise_id");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.HasKey("ExerciseEquipmentId")
                        .HasName("PK_seed_exercise_equipment");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ExerciseId", "EquipmentId")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_exercise_equipment");

                    b.ToTable("exercise_equipment", "library");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.ExerciseMuscleEntity", b =>
                {
                    b.Property<Guid>("ExerciseMuscleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exercise_muscle_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exercise_id");

                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("muscle_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("role");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("ExerciseMuscleId")
                        .HasName("PK_seed_exercise_muscles");

                    b.HasIndex("MuscleId");

                    b.HasIndex("ExerciseId", "MuscleId", "Role")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_exercise_muscles");

                    b.ToTable("exercise_muscles", "library");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.FoodCategoryEntity", b =>
                {
                    b.Property<Guid>("FoodCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("food_category_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name_en");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<string>("RecordScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("record_scope");

                    b.Property<string>("SeedKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("seed_key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("source");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("source_version");

                    b.HasKey("FoodCategoryId")
                        .HasName("PK_seed_food_categories");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_food_categories_seed");

                    b.ToTable("food_categories", "library");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.FoodEntity", b =>
                {
                    b.Property<Guid>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("food_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<decimal>("CalculationQuantity")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("calculation_quantity");

                    b.Property<Guid>("CalculationUnitId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("calculation_unit_id");

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("calories");

                    b.Property<decimal>("Carbs")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("carbs");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("fat");

                    b.Property<decimal?>("Fiber")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("fiber");

                    b.Property<Guid>("FoodCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("food_category_id");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name_en");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("protein");

                    b.Property<string>("RecordScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("record_scope");

                    b.Property<string>("SeedKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("seed_key");

                    b.Property<decimal>("ServingQuantity")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("serving_quantity");

                    b.Property<Guid>("ServingUnitId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("serving_unit_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("slug");

                    b.Property<decimal?>("Sodium")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("sodium");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("source");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("source_version");

                    b.Property<decimal?>("Sugar")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("sugar");

                    b.HasKey("FoodId")
                        .HasName("PK_seed_foods");

                    b.HasIndex("CalculationUnitId");

                    b.HasIndex("FoodCategoryId");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_foods_seed");

                    b.HasIndex("ServingUnitId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_foods_slug");

                    b.ToTable("foods", "library");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.FoodUnitEntity", b =>
                {
                    b.Property<Guid>("FoodUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("food_unit_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<decimal>("BaseQuantity")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("base_quantity");

                    b.Property<string>("BaseUnitCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("base_unit_code");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("code");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("dimension");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name_en");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<string>("RecordScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("record_scope");

                    b.Property<string>("SeedKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("seed_key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("source");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("source_version");

                    b.HasKey("FoodUnitId")
                        .HasName("PK_seed_food_units");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_food_units_code");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_food_units_seed");

                    b.ToTable("food_units", "library");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.GymAuditEventEntity", b =>
                {
                    b.Property<Guid>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("audit_event_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("OccurredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("occurred_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RequestId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("request_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("result");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("target_type");

                    b.HasKey("AuditEventId")
                        .HasName("PK_gym_audit_events");

                    b.ToTable("events", "audit");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.GymContextEntity", b =>
                {
                    b.Property<Guid>("GymContextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("gym_context_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ControlPlaneGymId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("control_plane_gym_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("GymCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("gym_code");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("provisioning")
                        .HasColumnName("status");

                    b.Property<string>("TimezoneName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasDefaultValue("Africa/Cairo")
                        .HasColumnName("timezone_name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("GymContextId")
                        .HasName("PK_core_gym_context");

                    b.HasIndex("ControlPlaneGymId")
                        .IsUnique()
                        .HasDatabaseName("UQ_core_gym_context_control_plane_id");

                    b.HasIndex("GymCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_core_gym_context_code");

                    b.ToTable("gym_context", "core");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.GymUserEntity", b =>
                {
                    b.Property<Guid>("GymUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("gym_user_id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ControlPlaneUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("control_plane_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("display_name");

                    b.Property<DateTime?>("LastPermissionSyncAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_permission_sync_at_utc");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("GymUserId")
                        .HasName("PK_auth_gym_users");

                    b.HasIndex("ControlPlaneUserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_auth_gym_users_control_plane_user");

                    b.HasIndex("Status", "ControlPlaneUserId")
                        .HasDatabaseName("IX_auth_gym_users_status");

                    b.ToTable("gym_users", "auth");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.LevelEntity", b =>
                {
                    b.Property<Guid>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("level_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("code");

                    b.Property<string>("LevelType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("level_type");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name_en");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<string>("RecordScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("record_scope");

                    b.Property<string>("SeedKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("seed_key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("source");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("source_version");

                    b.HasKey("LevelId")
                        .HasName("PK_seed_levels");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_levels_seed");

                    b.HasIndex("LevelType", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_levels_type_code");

                    b.ToTable("levels", "library");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.MuscleEntity", b =>
                {
                    b.Property<Guid>("MuscleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("muscle_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<Guid>("MuscleGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("muscle_group_id");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name_en");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<string>("RecordScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("record_scope");

                    b.Property<string>("SeedKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("seed_key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("source");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("source_version");

                    b.HasKey("MuscleId")
                        .HasName("PK_seed_muscles");

                    b.HasIndex("MuscleGroupId");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_muscles_seed");

                    b.ToTable("muscles", "library");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.MuscleGroupEntity", b =>
                {
                    b.Property<Guid>("MuscleGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("muscle_group_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name_en");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<string>("RecordScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("record_scope");

                    b.Property<string>("SeedKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("seed_key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("source");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("source_version");

                    b.HasKey("MuscleGroupId")
                        .HasName("PK_seed_muscle_groups");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_seed_muscle_groups_seed");

                    b.ToTable("muscle_groups", "library");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.SeedInstallationEntity", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("installation_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("checksum_sha256");

                    b.Property<DateTime>("InstalledAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("installed_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int")
                        .HasColumnName("record_count");

                    b.Property<string>("SeedDomain")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("seed_domain");

                    b.Property<string>("SeedVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("seed_version");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("source_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("InstallationId")
                        .HasName("PK___seed_installations");

                    b.HasIndex("SeedDomain", "SeedVersion")
                        .IsUnique()
                        .HasDatabaseName("UQ___seed_installations");

                    b.ToTable("__seed_installations", "library");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.AnatomyMappingEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.MuscleEntity", "Muscle")
                        .WithMany()
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.ExerciseEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.ExerciseCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.LevelEntity", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.MuscleEntity", "PrimaryMuscle")
                        .WithMany()
                        .HasForeignKey("PrimaryMuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Level");

                    b.Navigation("PrimaryMuscle");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.ExerciseEquipmentEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.EquipmentEntity", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.ExerciseEntity", "Exercise")
                        .WithMany("Equipment")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.ExerciseMuscleEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.ExerciseEntity", "Exercise")
                        .WithMany("Muscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.MuscleEntity", "Muscle")
                        .WithMany()
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.FoodEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.FoodUnitEntity", "CalculationUnit")
                        .WithMany()
                        .HasForeignKey("CalculationUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.FoodCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("FoodCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.FoodUnitEntity", "ServingUnit")
                        .WithMany()
                        .HasForeignKey("ServingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalculationUnit");

                    b.Navigation("Category");

                    b.Navigation("ServingUnit");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.MuscleEntity", b =>
                {
                    b.HasOne("LogicFit.Infrastructure.Persistence.Entities.MuscleGroupEntity", "MuscleGroup")
                        .WithMany("Muscles")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.ExerciseEntity", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Muscles");
                });

            modelBuilder.Entity("LogicFit.Infrastructure.Persistence.Entities.MuscleGroupEntity", b =>
                {
                    b.Navigation("Muscles");
                });
#pragma warning restore 612, 618
        }
    }
}
